
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CANVAS CIRCLE IMG LINE NUMBER OVAL QUOT RECT TEXT WRDexpression : NUMBERcolor : QUOT WRD QUOTx-coor : NUMBERy-coor : NUMBERradius : NUMBERexpression : CANVAS expression expression colorexpression : LINE x-coor y-coor x-coor y-coor colorexpression : CIRCLE x-coor y-coor radius colorexpression : OVAL x-coor y-coor x-coor y-coor colorexpression : RECT x-coor y-coor x-coor y-coor colorexpression : TEXT x-coor y-coor WRDexpression : IMG expression expression expression expression'
    
_lr_action_items = {'NUMBER':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20,21,22,23,25,26,28,31,32,33,34,37,40,41,42,43,44,],[2,-1,2,12,12,12,12,12,2,2,20,-3,20,20,20,20,2,12,-4,30,12,12,2,-6,20,20,20,-11,2,-8,-12,-2,-7,-9,-10,]),'CANVAS':([0,2,3,9,10,17,25,26,33,34,37,40,41,42,43,44,],[3,-1,3,3,3,3,3,-6,-11,3,-8,-12,-2,-7,-9,-10,]),'LINE':([0,2,3,9,10,17,25,26,33,34,37,40,41,42,43,44,],[4,-1,4,4,4,4,4,-6,-11,4,-8,-12,-2,-7,-9,-10,]),'CIRCLE':([0,2,3,9,10,17,25,26,33,34,37,40,41,42,43,44,],[5,-1,5,5,5,5,5,-6,-11,5,-8,-12,-2,-7,-9,-10,]),'OVAL':([0,2,3,9,10,17,25,26,33,34,37,40,41,42,43,44,],[6,-1,6,6,6,6,6,-6,-11,6,-8,-12,-2,-7,-9,-10,]),'RECT':([0,2,3,9,10,17,25,26,33,34,37,40,41,42,43,44,],[7,-1,7,7,7,7,7,-6,-11,7,-8,-12,-2,-7,-9,-10,]),'TEXT':([0,2,3,9,10,17,25,26,33,34,37,40,41,42,43,44,],[8,-1,8,8,8,8,8,-6,-11,8,-8,-12,-2,-7,-9,-10,]),'IMG':([0,2,3,9,10,17,25,26,33,34,37,40,41,42,43,44,],[9,-1,9,9,9,9,9,-6,-11,9,-8,-12,-2,-7,-9,-10,]),'$end':([1,2,26,33,37,40,41,42,43,44,],[0,-1,-6,-11,-8,-12,-2,-7,-9,-10,]),'QUOT':([2,18,20,26,29,30,33,35,36,37,38,39,40,41,42,43,44,],[-1,27,-4,-6,27,-5,-11,41,27,-8,27,27,-12,-2,-7,-9,-10,]),'WRD':([20,24,27,],[-4,33,35,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,9,10,17,25,34,],[1,10,17,18,25,34,40,]),'x-coor':([4,5,6,7,8,19,22,23,],[11,13,14,15,16,28,31,32,]),'y-coor':([11,13,14,15,16,28,31,32,],[19,21,22,23,24,36,38,39,]),'color':([18,29,36,38,39,],[26,37,42,43,44,]),'radius':([21,],[29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser_dl.py',11),
  ('color -> QUOT WRD QUOT','color',3,'p_expression_color','parser_dl.py',15),
  ('x-coor -> NUMBER','x-coor',1,'p_expression_xcoor','parser_dl.py',19),
  ('y-coor -> NUMBER','y-coor',1,'p_expression_ycoor','parser_dl.py',23),
  ('radius -> NUMBER','radius',1,'p_expression_radius','parser_dl.py',27),
  ('expression -> CANVAS expression expression color','expression',4,'p_expression_canvas','parser_dl.py',31),
  ('expression -> LINE x-coor y-coor x-coor y-coor color','expression',6,'p_expression_line','parser_dl.py',36),
  ('expression -> CIRCLE x-coor y-coor radius color','expression',5,'p_expression_circle','parser_dl.py',40),
  ('expression -> OVAL x-coor y-coor x-coor y-coor color','expression',6,'p_expression_oval','parser_dl.py',48),
  ('expression -> RECT x-coor y-coor x-coor y-coor color','expression',6,'p_expression_rectangle','parser_dl.py',52),
  ('expression -> TEXT x-coor y-coor WRD','expression',4,'p_expression_text','parser_dl.py',56),
  ('expression -> IMG expression expression expression expression','expression',5,'p_expression_image','parser_dl.py',61),
]
